### ISSUE TITLE
convert all audio files within a folder

### ISSUE THREAD

**Issue by jung921** [kn007/silk-v3-decoder#1]
If I put all my .aud/ .amr files in one folder, how can I convert all audio files within a folder?

**Comment by kn007** [comment]
Do you mean need to covert all audio files in one folder?
And aud may not a silk v3 encode, it will not support by my convert shell script.
My convert shell script only support decode the silk v3 encode files.

**Comment by kn007** [comment]
Oh, I had received your email, convert all audio files in one folder need write a new shell script(or update the converter shell script), I will do this later.

**Comment by kn007** [comment]
Finished in https://github.com/kn007/silk-v3-decoder/commit/af725fbe9bb99ee0aff8dd6e393c32ba86449a03

**Comment by kn007** [comment]
If the situation allows, hope to send several .aud files for me to test it. 
Maybe can add AMR convert support.

**Comment by jung921** [comment]
Hi there, thank you so much for your prompt support and update. this is fantastic!!!
When I try the new code, I get following error message.
this is when i tried to convert one file.

`$ sh convert.sh msg_572312032515d0ef979036a102.amr mp3
convert.sh: line 11: $'\r': command not found
convert.sh: line 18: $'\r': command not found
convert.sh: line 21: $'\r': command not found
convert.sh: line 59: syntax error: unexpected end of file
`

When I try to convert all audio files from the audio folder, and put the converted file into the audio-converted folder, I also get the following error message.

`$ sh convert.sh audio audio-converted/ mp3
convert.sh: line 11: $'\r': command not found
convert.sh: line 18: $'\r': command not found
convert.sh: line 21: $'\r': command not found
convert.sh: line 59: syntax error: unexpected end of file`

Your original script still works fine with the single amr audio file (which is silk_v3)

**Comment by kn007** [comment]
Sorry about that, maybe because unicode problem, I will re-upload script file later

**Comment by kn007** [comment]
It's working for me.
Please note that the script name has been changed.

**Comment by jung921** [comment]
Weird...

I changed the script name and tried again but still having the same issue for a single SILK_V3 codec file.

If I try with your original source code, it works fine without any issues.

**For single file
**`$ sh converter.sh msg_572312032515d0ef979036a102.amr mp3`

`converter.sh: line 11: $'\r': command not found
converter.sh: line 18: $'\r': command not found
converter.sh: line 21: $'\r': command not found
converter.sh: line 59: syntax error: unexpected end of file
`

**For folder
**

```
$ sh converter.sh audio audio-converted  mp3
converter.sh: line 11: $'\r': command not found
converter.sh: line 18: $'\r': command not found
converter.sh: line 21: $'\r': command not found
converter.sh: line 59: syntax error: unexpected end of file
```

**Comment by jung921** [comment]
Sorry, My bad. I re-cloned this repo as per your suggestion and it works fine. 
Not sure why it didn't work when I just changed the sh script though. 

Many thanks once again!

**Comment by kn007** [comment]
hmm, maybe you can try this: 

https://kn007.net/converter_ansi.sh

or

https://kn007.net/converter_utf-8.sh
