### ISSUE TITLE
同一个文件在不同机器上面 转码结果不同

### ISSUE THREAD

**Issue by lilaizhencn** [kn007/silk-v3-decoder#10]
微信小程序录制的silk文件，在centos上无法转为mp3 提示是可能不是一个v3文件，在mac上执行转码可以。

**Comment by kn007** [comment]
我博客里面有提到过，评论里。
因为每台机的配置不同，ffmpeg会选择不同的输出方式，cpu越好，输出的更高，如果你想强制多少就自行指定。
windows最新版本已经强制指定了。
另外这种并非bug，而是大部分转码器通用特性，我就关闭这个issue了。

**Comment by lilaizhencn** [comment]
恩，了解了我去看一下。
