### ISSUE TITLE
同样的执行程序 同样的解析文件 mac上面可以work 但部署到ubuntu上面就报错maybe not a silk v3 encoded file

### ISSUE THREAD

**Issue by ivanthing** [kn007/silk-v3-decoder#13]
如题

**Comment by ivanthing** [comment]
测试文件link http://purplecow.io/test/254d7c2136bfba4522e350f529f2482c

**Comment by kn007** [comment]
你用mac可以？
我笑了。

你自己看看你自己测试文件，用记事本打开看看
```
data:audio/webm;base64,
```
这是silk v3？？？
解密后用webm转码，或者最新版ffmpeg转码就行了。

**Comment by kn007** [comment]
你mac的成功的唯一可能原因就是因为最新版的ffmpeg可以解码webm

**Comment by kn007** [comment]
我这个是解码silk v3，但不是为webm服务的。你需要随机应变

**Comment by ivanthing** [comment]
好的 感谢 我看一下
