### ISSUE TITLE
Readme写的不好

### ISSUE THREAD

**Issue by TopCoderMyDream** [kn007/silk-v3-decoder#17]
希望可以列举出更明确的解决方式,哪个平台,下载哪些文件,各语言如何调用等.
全网就你一这一个可以转码,你写的说明不太好,我一头雾水不知如何所措,本来就是cmd可以完成的一件事情,却会出很多问题.

**Comment by kn007** [comment]
你可以fork后提交PR，如果你觉得你能写得更好
