### ISSUE TITLE
Mac下使用报错Convert 178.aud.silk false, maybe not a silk v3 encoded file.

### ISSUE THREAD

**Issue by Jokery** [kn007/silk-v3-decoder#19]
在windows虚拟机下使用windows程序成功转换，所以语音文件本身应该没有问题；
环境是zsh，gcc和ffmpeg都有

**Comment by kn007** [comment]
所以你这个文件是小程序语音吗？

**Comment by kn007** [comment]
用beta版本转换呢？

**Comment by kn007** [comment]
如果是小程序语音请自行关闭issue。因为小程序现在基本上不采用silk v3编码了，自然就提示无法转换，因为非silk v3编码。
转换的话，请先用base64解码，然后将得到webm编码文件转换为其他格式。

如果非小程序语音，你可以试试beta版本，beta版本转换，看看能否播放。

**Comment by kn007** [comment]
疑似无关Bug且超过20小时无回复的ISSUE将会被关闭。

**Comment by Jokery** [comment]
抱歉回复的不太及时，是微信普通语音，我用windows下的win程序可以正确解码，但是用那个sh脚本会出错；当然并不影响正常使用，毕竟有一个可以用的。

**Comment by kn007** [comment]
那麻烦你用下beta版本试试。

**Comment by Jokery** [comment]
迟点我在同一台机器上试试再答复你

**Comment by kn007** [comment]
好的，没问题。
