### ISSUE TITLE
微信小程序录音 silk 无法转 mp3.

### ISSUE THREAD

**Issue by liumingzhij26** [kn007/silk-v3-decoder#21]
linux centos 6.5版本

使用小程序录音之后的格式为 silk，文件的Header 为
`data:audio/webm;base64`
 ffmpeg 安装与转码都是正常的
我看了sh脚本，第一步是
 `# ./silk/decoder test.slk test.pcm`
 会提示`Error: Wrong Header ata:audi`
这一步错误，就无法进行下一步了

**Comment by liumingzhij26** [comment]
大哥，刚才赞助了100块

**Comment by kn007** [comment]
小程序不是silk v3编码。
先base64解码，然后用最新版ffmpeg直接转换就行了。

**Comment by liumingzhij26** [comment]
我已经搞定了，把data:audio/webm;base64解码，保存为silk 文件，然后写转就可以了

**Comment by liumingzhij26** [comment]
多谢

**Comment by kn007** [comment]
感谢赞助，非常感谢

**Comment by kn007** [comment]
不客气，那我关闭了
