### ISSUE TITLE
在Linux上编译成功了，也运行成功。但是把编译好的文件下载回来，再传回服务器，就不行了。。。

### ISSUE THREAD

**Issue by paraself** [kn007/silk-v3-decoder#22]
你好，我对Linux系统和makefile这块儿不太熟悉。我所用的服务器，每次部署代码，之前的东西都会被清空掉，因此，每一次部署，就得编译一次您的这个解码器。所以我就想把linux系统编译好的文件下载回来。
我注意到似乎生成的文件都在silk这个目录下，主要包含有decoder这个可执行文件，因此我就把这个文件夹整个下载回来了。然后再作为已经编译好的程序，再上传回服务器。但是这个编译好的程序却不工作了，报错：maybe not a silk v3 encoded file。。。。
请问一下我哪里做错了，是不是遗漏了什么？

**Comment by kn007** [comment]
docker？

你这属于编译问题，编译的时候，你需要静态化。
或者你在服务器编译完，下下来，下次要用再上传上去。
你在本地编译，与服务器的运行库不同，自然运行不了，会报错。
其实编译一下也花不了多长时间。

最好是静态化编译，免得你重生成的系统与编译时系统不同，那样也是不行的。

**Comment by paraself** [comment]
> 或者你在服务器编译完，下下来，下次要用再上传上去。
我现在就是这么做的呢，我注意到服务器上编译生成了decoder这个可执行文件，我下载下来了。再次上传回去，sh脚本因为检测到decoder而不去编译。但是这个decoder文件却无法正确执行导出。
所以想问一下，是不是除了生成了decoder，还在别的目录生成了一些依赖的文件？
静态化我也去看看，谢谢您的指点啦。

**Comment by kn007** [comment]
哦，那说明你系统每次的静态库链接有偏差。我的最终文件就是decoder。
我静态编译一个给你，你试试看
[decoder.zip](https://github.com/kn007/silk-v3-decoder/files/1185625/decoder.zip)

**Comment by paraself** [comment]
TT还是不行，和之前报错的一模一样
`-e \e[0;33m[Warning]\e[0m Convert /home/leanengine/app/tmp/0db951a8a1660977e21f2f46a322ef12 false, maybe not a silk v3 encoded file.`

**Comment by kn007** [comment]
语音文件确定没问题？不用我的脚本，直接命令行呢？
我这边编译完，单文件拿到别处很正常。

**Comment by kn007** [comment]
脚本调用decoder的位置是./silk/decoder哦
我给你的程序需要解压后上传到服务器，你上传后，运行一次，看正不正常

**Comment by paraself** [comment]
我反复试了多次，发现还是不行。已经确认了语音文件没问题。不用脚本直接用你的decoder似乎还是无法执行。
应该是因为
`$cur_dir/silk/decoder "$1" "$1.pcm" > /dev/null 2>&1`
这一句没有生成对应的pcm文件。
我想会不会是权限问题？可能直接在服务器上编译的decoder具有更多的权限，而自己上传的decoder不具有写权限？
能不能在这句话
`$cur_dir/silk/decoder "$1" "$1.pcm" > /dev/null 2>&1`
之前，对decoder的权限做一个检查？考虑到有的时候，decoder是预先编译好的情况。
不好意思，不会shell脚本，麻烦您看一下如何修改一下，辛苦啦。

**Comment by kn007** [comment]
...
兄弟，你这个就有点白了。。。。。。
上传到silk目录里后，需要
chmod +x ./silk/decoder

**Comment by paraself** [comment]
解决了！多谢您了。
TT真的是不太懂linux系统，也不会c语言什么的。。。之前只做过游戏和前端项目。。。看来要补补了。。。

**Comment by paraself** [comment]
不过建议在sh脚本里，还是检测一下权限，目前由于权限不够而无法写入，都会报成

**Comment by kn007** [comment]
脚本是本身是带权限编译，无需检查权限。
多此一举了。。。
