### ISSUE TITLE
希望有更多的朋友能提供大量小程序语音或者webm编码的样本给我，谢谢

### ISSUE THREAD

**Issue by kn007** [kn007/silk-v3-decoder#24]
因 issue #23 引发的一个需求，目前解码和编码webm给小程序使用时，存在一些问题。

需要一些语音样本，提供到此。谢谢各位支持。

主要是因为我本身不从事微信小程序开发，也不研究微信和QQ。

只是业余爱好，对语音文件分析，编解码。所以需要一些帮助。

**Comment by kn007** [comment]
如果有哪位能直接提供编解码方法，那就更好了，目前不知微信用着哪个版本的webm。

**Comment by yuemeTM** [comment]
http://redpack-1253955196.cosgz.myqcloud.com/redpack/tmp_a8fee2ba499f359be48210cf56586ba4.silk
http://redpack-1253955196.cosgz.myqcloud.com/redpack/tmp_1111ca5399731311e37e0bf3c6fdd8da.silk
http://redpack-1253955196.cosgz.myqcloud.com/redpack/tmp_2081cbc464eb74c7a72777b572bb9f86.silk
http://redpack-1253955196.cosgz.myqcloud.com/redpack/tmp_35f9d033a54dbc63ee67aa1bc56d1310.silk

最近在做开发。。。一开始可以用你的工具进行decode。。。后面突然decode失败。。。

**Comment by tl54577** [comment]
[te.zip](https://github.com/kn007/silk-v3-decoder/files/1240504/te.zip)

**Comment by kn007** [comment]
@tl54577 收到，你这又是个新样例。样本太少，研究不出。
做了一些混搅，还是webm，但偏移量测不出。

**Comment by kn007** [comment]
@yuemeTM 最新的1.0.2.3应该解决这一问题了。

**Comment by tl54577** [comment]
@kn007 现在小程序的源文件都是这样，都不知道在linux怎么转换了！

**Comment by kn007** [comment]
@tl54577 本来是可以的，但是他现在做了偏移量混淆，导致文件结构变了，所以转换不了。。。
最好能有人问下官方，因为我不是开发者，问不到。

**Comment by tl54577** [comment]
@kn007 微信开发问题只能在社区提问，官方根本都不理！心酸

**Comment by kn007** [comment]
@tl54577 。。不知他混淆的意义在哪？
怕别人做伪证？

**Comment by tl54577** [comment]
@kn007 有程序员说，将文件中的 data:audio/webm;base64, 字符串去掉，然后base64解码，最后用ffmpeg转换成MP3格式，但是我还是没测试成功，柯南你试试呢

**Comment by kn007** [comment]
@tl54577 这个程序员没说错啊。
但是最新的微信小程序语音做了偏移量混淆，你自己对比一下就知道了。

**Comment by tl54577** [comment]
@kn007 玛德，公司现在必须要这个东西，真让我很难堪，微信真坑哥！[](url)

**Comment by kn007** [comment]
@tl54577 我也没办法，只能微信能公开方法，不然只能自寻搜索。
我也是业余爱好就弄弄，也没什么时间。

**Comment by languiji** [comment]
微信小程序的silk  终于搞清楚了，直接打开文件  去掉data:audio/webm;base64，然后base64解码  然后把后缀改成.webm 就能通过audio标签或者组件播放......

**Comment by kn007** [comment]
@languiji 。。我们谈论的是非标准webm文件，谢谢。

你有下过这个文件测试过么。
https://github.com/kn007/silk-v3-decoder/files/1240504/te.zip

**Comment by languiji** [comment]
@kn007 测试过了，不好意思  我不太懂，所以发的内容可能不太合适。对不起

**Comment by kn007** [comment]
你那个可以正常播放很可能是正常的。
微信小程序有一部分语音仍然是正常的webm，一部分是混淆的。我们现在就想知道他是怎么混淆的。
你说测试过，是指用你自己的文件，还是说，用了 te.zip 的文件。

**Comment by languiji** [comment]
@kn007 测试了 这个te.silk 用base64解码  改webm无法播放

**Comment by kn007** [comment]
@languiji 嗯，麻烦你了。
如果以后你有类似这种不能播放的文件，并且不具隐私性的，可以留一份给我。

**Comment by languiji** [comment]
好的   我随时联系您~~~

**Comment by tl54577** [comment]
@languiji 你把你的silk文件发我一份呢 1023745650@qq.com

**Comment by languiji** [comment]
好的。我回家给您多发一些 
------------------ Original ------------------

**Comment by fanyinghao** [comment]
我这里有一些来自微信小程序的录音文件：
https://cdn.jiuyin.wecode.net.cn/upload/audio/85ee7f26-4c8d-4435-b092-0b6c9bb58828.silk
https://cdn.jiuyin.wecode.net.cn/upload/audio/b8f7684d-ec27-4eb0-a527-ab6ebdaafe87.silk
https://cdn.jiuyin.wecode.net.cn/upload/audio/aa4b899f-e6f3-4abf-bf8e-a6d1d5128e48.silk
https://cdn.jiuyin.wecode.net.cn/upload/audio/e956388f-399a-42f0-bb7d-1895be16f381.silk
https://cdn.jiuyin.wecode.net.cn/upload/audio/6a7eabff-b086-4868-afe8-3a448389d630.silk
https://cdn.jiuyin.wecode.net.cn/upload/audio/4c786531-fe8e-4d74-91a2-a99ec558dc23.silk

微信客户端和机器信息：
https://cdn.jiuyin.wecode.net.cn/upload/20170828003158.png

希望这些信息能帮助到，因为我也急需你工具的协作，这些silk文件都不能转码到pcm！

**Comment by tl54577** [comment]
@languiji 你发我的我没收到啊

**Comment by languiji** [comment]
@kn007 523579987@qq.com 这个邮箱发的，蓝轨迹silk文件集合

**Comment by tl54577** [comment]
@languiji 没收到，你发我这个 邮箱吧  1023745650@qq.com

**Comment by languiji** [comment]
@kn007 发过去了

**Comment by tl54577** [comment]
@languiji 你这不是小程序的silk文件吧

**Comment by languiji** [comment]
@kn007 是的   是小程序录制上传到服务器的

**Comment by tl54577** [comment]
@languiji 你这是标准的silk文件，用converter.sh可以直接转的

**Comment by languiji** [comment]
但是转出来的 大小都是0

**Comment by tl54577** [comment]
@languiji 我刚刚试了，转出来是对的，而且可以正常播放

**Comment by languiji** [comment]
我是直接在linux 下执行的命令  我转出来大小都是0  方便您的命令发给我一下吗？

**Comment by fanyinghao** [comment]
@tl54577 我在Windows上跑silk_v3_decoder.exe，但是提示Error: Wrong Header ata:audi ，不能转。我转的文件是上面post的那些。知道原因吗？

**Comment by tl54577** [comment]
@languiji  sh.converter.sh   xxx.silk mp3 直 接就可以转你发我的silk文件

**Comment by languiji** [comment]
@kn007 好的  谢谢

**Comment by kn007** [comment]
@fanyinghao 因为不是silk v3编码，所以转不了。你这个问题和 #23 ，没什么区别。都是基础问题。在我博客都被问了几十遍，只要看看评论，或者勤于搜索就行的事。

你们能不能不是同一issue的主题，别老评论行不行？评论一些符合主题的话题，好吧。

小白话题自己多看看就知道了。不耻下问是好事的，但只想伸手，我不欢迎。

**Comment by liuzhuan** [comment]
@kn007 经过一些实验，发现微信小程序的录音格式后缀虽都是 `.silk`，但在不同平台内容格式有差异。具体来说：

* macOS 的开发者工具，录制的音频文件，文件头是 `data:audio/webm;base64,`
* iOS 和 Android 真机录制的音频，文件头是 `^B#!SILK_V3`

这是 2017.08.31 的实验结果，不知道后续会不会变动。

仅供参考。

**Comment by kn007** [comment]
谢谢 @liuzhuan
这个已经是已知的了，目前问题是有部分文件他做了偏移，解密不了。

**Comment by zhibinm** [comment]
@liuzhuan 那这样，只要考虑真机的音频转换就可以了吗？因为用户不可能用开发者工具是吧

**Comment by zhibinm** [comment]
@kn007 发现的偏移是类型的文件，是data:audio/webm;base64这种开头还是 ^B#!SILK_V3 ？？目前真机测试是发 ^B#!SILK_V3 这种开头的。测试环境才是data:audio/webm;base64

**Comment by kn007** [comment]
都有，没有webm最好。

**Comment by kn007** [comment]
据说，目前小程序移动端仍为silk v3编码的语音，SDK电脑端测试时有可能不是，所以关闭这个issue了。

**Comment by zengqingf** [comment]
@yuemeTM 你们语音转文字用的啥技术啊
