### ISSUE TITLE
您好~MP3提示转换成功，但是mp3文件大小为0

### ISSUE THREAD

**Issue by languiji** [kn007/silk-v3-decoder#25]
通过您的工具提示成功转换了mp3，文件也生成，但是大小为0，且无法播放，请问一下有解决方案吗？感谢您。

**Comment by kn007** [comment]
你用了哪个脚本？
还是用了silk2mp3

**Comment by languiji** [comment]
linux下的 conventer.sh  提示finished  文件生成后大小是0,文件来源是小程序录音上传的可播放的文件。.silk格式 
------------------ Original ------------------

**Comment by kn007** [comment]
首先，beta脚本不是给小白用的。
只是个很简单的amr头修复复现。

如果你用converter，请提供环境信息。
win也解不了，请参考置顶issue。

**Comment by kn007** [comment]
现有小程序语音已非silk v3编码。
这个项目只考虑silk v3编码，其他可以使用win版本。win版本为本项目源码实际应用。

**Comment by languiji** [comment]
那请问小程序的silk  是不是没办法在linux下转码了？

**Comment by kn007** [comment]
可以啊，base64解码后，用webm解码。

**Comment by languiji** [comment]
可以具体说说步骤吗？第一次涉及到这个问题，确实不太了解，感谢您了

**Comment by kn007** [comment]
用你熟悉的语言：
1.去掉源文件data:audio/webm;base64,输出
2.把第一步的文件进行base64解码输出
3.将第三步的文件使用webm解码输出成mp3

**Comment by tl54577** [comment]
@kn007 webm怎么解码输出成mp3

**Comment by kn007** [comment]
@tl54577 ...
支持webm的编码器都行啊。最新版ffmpeg也支持。

**Comment by zhibinm** [comment]
现在小程序上传的语音文件格式不是silk了吗

**Comment by kn007** [comment]
很难说自己看。我不研究这个。

**Comment by zhibinm** [comment]
谢谢，我先了解下

**Comment by xablackcat** [comment]
maybe ffmpeg no format handler for wav
exec执行转换输出这个是什么问题呢，谢谢

**Comment by kn007** [comment]
@xablackcat 如英文所述，或者ffmpeg不存在，无权限执行

**Comment by xablackcat** [comment]
我在shell界面执行转换都正常，但是在php里面就是提示这个

**Comment by kn007** [comment]
@xablackcat 我上面写的很清楚了。
你说的这情况属于权限问题

**Comment by xablackcat** [comment]
这个应该怎么调整呢，我对linux不是很熟悉，谢谢

**Comment by kn007** [comment]
@xablackcat 授权给php

**Comment by xablackcat** [comment]
我试试，谢谢
