### ISSUE TITLE
Windows - silk2mp3 encode wav audio

### ISSUE THREAD

**Issue by GHkIT** [kn007/silk-v3-decoder#26]
Files：
-ffmpeg.exe
-lame.exe
-silk_v3_decoder.exe
-silk_v3_encoder.exe
-silk2mp3.exe
-test.wav

1. 当使用silk2mp3编码WAV音频时出现停留在0％的现像。
2. 使用encoder,decoder 转出的MP3音频无法播放。
  `silk_v3_encoder test.wav test.amr -Fs_API 24000 -tencent`
  `silk_v3_decoder test.amr test.mp3 -Fs_API 24000`

-test.wav
[test.zip](https://github.com/kn007/silk-v3-decoder/files/1269375/test.zip)

**Comment by kn007** [comment]
哦，这个问题，在最新版本解决了，忘记传上来了。请你过一小时后再查看。
encoder、decoder你明不明白作用？？？
他并不能转成mp3，谢谢。

**Comment by GHkIT** [comment]
对不起，让你误会，MP3副档名属于个人项目中的限制（明白实际上仍是WAV）
想要说明的是wav encoder silk，再解码器是无法播放的，而且二进制与源音源不相同（不可逆）

**Comment by kn007** [comment]
没明白意思

**Comment by GHkIT** [comment]
[TestFiles.zip](https://github.com/kn007/silk-v3-decoder/files/1273825/TestFiles.zip)
silk_v3_encoder test.wav test.amr -Fs_API 24000 -tencent
silk_v3_decoder test.amr test.wav -Fs_API 24000

解码wav无法播放,而且大小不一

**Comment by kn007** [comment]
还是没明白你的意思。。。你先解释一下你理解的silk_v3_encoder和silk_v3_decoder的作用是什么

**Comment by kn007** [comment]
或者我再解释一遍吧。。
silk_v3_encoder，将任意符合标准的pcm编码成silk v3；
silk_v3_decoder，将任意符合已知标准的silk v3解码成标准pcm。

有什么疑问么。

**Comment by kn007** [comment]
回到问题，如果
```
silk_v3_encoder test.wav test.amr -Fs_API 24000 -tencent
```
的test.wav不是silk v3，那便毫无意义。

**Comment by kn007** [comment]
还有标题你写着`Windows - silk2mp3`，这个silk2mp3有什么关系，你问的问题，你通过软件转的转不了吗？

**Comment by GHkIT** [comment]
> 或者我再解释一遍吧。。
silk_v3_encoder，将任意符合标准的pcm编码成silk v3；
silk_v3_decoder，将任意符合已知标准的silk v3解码成标准pcm。
还有什么疑问么。

疑问是test.wav编码成丝v3后再进行解码，解码后无法播放，而且大小不一。
已提供样本

>还有标题你写着Windows - silk2mp3，这个silk2mp3有什么关系，你问的问题，你通过软件转的转不了吗？

因为此前silk2mp3的问题（停留在0％），'个人'认为與decoder解码失敗有关连 故在一个问题上
silk2mp3的问题确定已解决，问题已结束。
对不起，我会再提交新问题.

**Comment by kn007** [comment]
文件不一样大小，是正常的。

你test.wav是什么编码，我问你

**Comment by kn007** [comment]
麻烦你描述时，描述下你的目的，你的所有文件的编码类型。

**Comment by kn007** [comment]
我大概明白你的意思了。
如果你的test.wav不是s16le的pcm编码，那么编码成silk v3必定有问题。

**Comment by kn007** [comment]
正确步骤
test.wav => test.pcm
test.pcm => test.silk
test.silk => test.pcm
test.pcm => test.wav

**Comment by GHkIT** [comment]
明白，
总结确实是我不理解编解码的需求，对不起。
谢谢你的耐心。

**Comment by kn007** [comment]
客气了。

**Comment by EdenLiang** [comment]
> 明白，
> 总结确实是我不理解编解码的需求，对不起。
> 谢谢你的耐心。
> 
> # Remark
> ### input.wav => output.pcm
> `ffmpeg -i input.wav -f s16le -ar 24000 -ac 2 output.pcm`
> 
> ### output.pcm => output.silk
> `silk_v3_encoder output.pcm output.silk -tencent`
> 
> ### output.silk => output.pcm
> `silk_v3_decoder output.silk output.pcm`
> 
> ### output.pcm => output.wav
> `ffmpeg -f s16le -ar 24000 -ac 2 -i output.pcm output.wav`
> 
> [temp.zip](https://github.com/kn007/silk-v3-decoder/files/1274306/temp.zip)

这段Remark非常棒
感谢
