### ISSUE TITLE
询问及需求：动态链接库版本

### ISSUE THREAD

**Issue by GHkIT** [kn007/silk-v3-decoder#28]
感谢作者的项目，对于我的帮助非常大（非商业）

看到作者说准备不维护，希望借着现在询问作者能否提供动态链接库版本（DLL），
包括提供Completed Handler用于整合到项目中？
因为我并不了解C语言，无法作出转换成DLL或是重写成其他语言。
虽然属伸手党行为，还望作者告知可否，谢谢

另,希望回復:https://github.com/kn007/silk-v3-decoder/issues/26

**Comment by kn007** [comment]
无此计划
