### ISSUE TITLE
silk encoder问题

### ISSUE THREAD

**Issue by railsfans** [kn007/silk-v3-decoder#31]
请教一下，我看了你的convert.sh脚本说明decoder过程是先将slik转成pcm，再将pcm转成mp3，如果encoder过程呢，具体是怎么一个流程，我编译出来的encoder可执行文件是将什么格式转成什么格式，我是linux平台，另外我看你的windows平台上有工具将mp3转成slik，但是我在小程序中没法播放这个windows平台上转出来的slik文件，请问是怎么一回事，谢谢。

**Comment by kn007** [comment]
首先，小程序语音并不是silk v3，或者说并不单单silk v3。你可以尝试编码成微信兼容的silk语音给小程序，但并不一定可以用。小程序还是较多采用base64编码webm。

encode过程：
input file=>pcm=>silk v3

非bug，关闭issue。

**Comment by railsfans** [comment]
恩，windows工具上面提供了各种选项，比如兼容qq微信、小程序等，我试了下用windows工具将mp3转成slik小程序也不能用，估计是微信端的问题，另外这个encode过程应该是没有pcm这个中间的文件产生把，直接调用编译好的encode产生的文件就是silk v3文件吧。

**Comment by kn007** [comment]
同decoder一样，encoder也只复制pcm与silk v3之间的转换。

**Comment by gavinliu** [comment]
我用在 silk 目录下 make encoder 编译的编码器，来编码 silk ，在微信播放是乱码。


```
./encoder 1.pcm 1.amr -Fs_API 16000 -packetlength 60 -rate 24000 -complexity 0
```

参数入上，也试过其他各种参数，也不行， @kn007 你知道是怎么回事吗？


另外我在 https://github.com/gaozehua/SILKCodec 这个源码编译出的 decoder 解不了，不知道你的 SILK 源码出自哪儿，或者是你做了什么处理？

**Comment by gavinliu** [comment]
刚刚对比了下你的 silk 源码，encoder 有个  -tencent ，牛逼啊 大佬，口一个

**Comment by kn007** [comment]
@gavinliu 我是正经人！
