### ISSUE TITLE
PHP执行 小程序的 silk 文件转 mp3，pcm 文件可以生成，mp3文件没有生成，可否告知如何解决

### ISSUE THREAD

**Issue by lindent** [kn007/silk-v3-decoder#35]
在CentOS 7上，通过root登录，执行命令，可以生成 pcm 和 MP3，通过 PHP执行的话，可以生成pcm文件，但是不生成 mp3 文件，提示 ： Convert ../data/upload/default/20180203/5a75d2c3817a1.silk false, maybe ffmpeg- no format handler for mp3.，可否告知如何解决，谢谢

**Comment by kn007** [comment]
权限问题，先补基础知识。
