### ISSUE TITLE
decoder文件无法执行

### ISSUE THREAD

**Issue by yanweitao** [kn007/silk-v3-decoder#36]
-bash: ./decoder: cannot execute binary file 
我在mac上可以正常使用，在centos上就不行了。

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core

**Comment by kn007** [comment]
没有GCC吧，或者你直接拿了mac上的decoder上去用了。
decoder默认是动态库，你不能拿在mac环境编译的程序，去别的系统上用（除非相同系统或者使用静态编译）

**Comment by yanweitao** [comment]
好的，谢谢大神
之前传到centos里的是mac用过后的压缩包。
刚才吧之前从github下载的master.zip直接传上去，就可以了。
还是首次编译导致的问题
对了，已经编译过的，直接删除decoder是不行的，其他文件也有影响。

**Comment by kn007** [comment]
嗯，你也可通过在silk目录下make clean清除预编译文件。这样就不用重新下载文件了。
