### ISSUE TITLE
mp3文件，转 SILK_V3 头的，amr格式文件，结果大小只有1K。

### ISSUE THREAD

**Issue by supperlitt** [kn007/silk-v3-decoder#38]
我使用下面的命令进行转换，mp3文件，拷贝到了。exe同目录下的。，很多命令都试过了，都只有1k大小，但是如果用软件就可用得到7K左右。因为我是web调用，所以求指导。。。

>silk_v3_encoder.exe td.mp3 td.silk -tencent

输出
>
********** Silk Encoder (Fixed Point) v 1.0.9.6 ********************
********** Compiled for 32 bit cpu *******************************
Input:                          td.mp3
Output:                         td.silk
API sampling rate:              24000 Hz
Maximum internal sampling rate: 24000 Hz
Packet interval:                20 ms
Inband FEC used:                0
DTX used:                       0
Complexity:                     2
Target bitrate:                 25000 bps
Packets encoded:                10
File length:                    0.200 s
Time for encoding:              0.013 s (6.497% of realtime)
Average bitrate:                31.800 kbps
Active bitrate:                 31.800 kbps

我应该用什么命令呢？

**Comment by supperlitt** [comment]
[td.zip](https://github.com/kn007/silk-v3-decoder/files/2079922/td.zip)
音频文件.mp3

**Comment by kn007** [comment]
看说明。
错误操作方式。

**Comment by supperlitt** [comment]
那应该如何解决呢？

**Comment by kn007** [comment]
看说明。
silk无法直接编码mp3啊，转成pcm先。

**Comment by supperlitt** [comment]
我是想用mp3z转成silk,意思就是mp3先转 pcm。然后在转 silk？

**Comment by kn007** [comment]
对的，跟解码同理。

**Comment by supperlitt** [comment]
确实，解码和编码都可以了，就是音频好像出问题了，没声音了。
>ffmpeg -i td.mp3 -f s16be -ar 8000 1.pcm

>silk_v3_encoder.exe 1.pcm td.silk

大神，那应该用哪种命令呀？

**Comment by kn007** [comment]
频率错了吧。你仔细看参数好吧。
这种说明很清楚的问题，我不会再答了。
