### ISSUE TITLE
[Warning] Convert /tmp/sample.silk false, maybe ffmpeg no format handler for wav.

### ISSUE THREAD

**Issue by flyjavacom** [kn007/silk-v3-decoder#40]
今天使用该项目提示[Warning] Convert /tmp/sample.silk false, maybe ffmpeg no format handler for wav.
我的指令是     sh converter_beta.sh /tmp/sample.silk wav
我在centos上操作，安装了ffmpeg 下载了gcc等环境，之前使用该命令转换成wav是成功的。

**Comment by kn007** [comment]
那就是权限问题，检查一下。
