### ISSUE TITLE
freebsd无法转换

### ISSUE THREAD

**Issue by mn3711698** [kn007/silk-v3-decoder#41]
您好，我在freebsd下进行转换，提示
root@VM_0_2_freebsd:/var/games/eoengroup/silk # sh /var/games/eoengroup/silk/convert.sh /var/games/eoengroup/static/data/1b2975ae7ef19ae7fc34f085aa479e4c.slk mp3
sh: cannot open /var/games/eoengroup/silk/convert.sh: No such file or directory

**Comment by kn007** [comment]
文件不存在，自己检查一下
