### ISSUE TITLE
编译问题？

### ISSUE THREAD

**Issue by mn3711698** [kn007/silk-v3-decoder#42]
会不会不兼容freebsd系统，导致编译出错了。我晚上用debain试试。要是您方便测试下freebsd系统那就太感谢了

下边是运行的命令及最后提示。

root@VM_0_2_freebsd:/var/games/eoengroup/silk # wget https://github.com/kn007/silk-v3-decoder/archive/master.zip

root@VM_0_2_freebsd:/var/games/eoengroup/silk # unzip master.zip

root@VM_0_2_freebsd:/var/games/eoengroup/silk # cd silk-v3-decoder-master/
root@VM_0_2_freebsd:/var/games/eoengroup/silk/silk-v3-decoder-master # cd silk/
root@VM_0_2_freebsd:/var/games/eoengroup/silk/silk-v3-decoder-master/silk # make

make: "/var/games/eoengroup/silk/silk-v3-decoder-master/silk/Makefile" line 91: warning: duplicate script for target "(,)" ignored
make: "/var/games/eoengroup/silk/silk-v3-decoder-master/silk/Makefile" line 36: warning: using previous script for "(,)" defined here
make: "/var/games/eoengroup/silk/silk-v3-decoder-master/silk/Makefile" line 92: Need an operator
make: "/var/games/eoengroup/silk/silk-v3-decoder-master/silk/Makefile" line 94: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /var/games/eoengroup/silk/silk-v3-decoder-master/silk

**Comment by mn3711698** [comment]
会不会不是没有文件，而是编译没有完成，导致找不到文件

**Comment by kn007** [comment]
压根不关编译事，就你上条issue就能看出来了。
