### ISSUE TITLE
期待增加微信开发工具语音转换

### ISSUE THREAD

**Issue by mn3711698** [kn007/silk-v3-decoder#44]
目前已用此工具在ubuntu上进行处理微信小程序的语音转换。在开发做测试的时候，发现微信开发工具上的语音不是标准的silk v3标准。没办法转换。手机上的微信小程序的语音可以转换。

**Comment by kn007** [comment]
找腾讯。
能不能先搜索？这个问题答过无数遍了。
sdk开发环境与实际环境生成的语音不同。
