### ISSUE TITLE
windows命令行

### ISSUE THREAD

**Issue by wutongshenyuan** [kn007/silk-v3-decoder#46]
如何在windows命令行下使用呢

**Comment by kn007** [comment]
github不是有么。。。
自己在cmd下，敲一下就知道了。

**Comment by wutongshenyuan** [comment]
谢谢 可是我敲出来的 语速特别快

**Comment by wutongshenyuan** [comment]
斗胆跟大哥要一下 au3 源码

**Comment by kn007** [comment]
参数有频率设置。
au3源码没有。硬盘坏了。

**Comment by wutongshenyuan** [comment]
我一开始一直坚信，silk_v3_decoder解码用多少采样率，lame编码就用多少采样率，一直不行，后来我尝试把silk_v3_decoder解码采样率固定，动态调整lame编码采样率，最终成功了，感谢大神指点
