### ISSUE TITLE
mac下编译失败

### ISSUE THREAD

**Issue by badboy-tian** [kn007/silk-v3-decoder#49]
![image](https://user-images.githubusercontent.com/2835129/51984182-aff1bc80-24d5-11e9-8892-90c10e8ea12e.png)

**Comment by kn007** [comment]
正常应该没问题，你换个gcc版本看看。没有mac，没有测试环境。

**Comment by badboy-tian** [comment]
Silk v3 Decoder Compile False, Please Check Your System For GCC
