### ISSUE TITLE
Windows Defender mark silk2mp3.exe as trojan

### ISSUE THREAD

**Issue by PaleNeutron** [kn007/silk-v3-decoder#50]
![screenshot](https://user-images.githubusercontent.com/8296331/52795221-516b3780-30ac-11e9-806d-427a814cc0ee.png)

**Comment by kn007** [comment]
误报来着的，回头我加上证书看看

**Comment by kn007** [comment]
你可以测试下最新版本 1.0.2.6，我测试没问题了。

**Comment by kn007** [comment]
如果还报也没办法了，这种属于误报。。。仁者见仁。

**Comment by PaleNeutron** [comment]
No problem now.

**Comment by SimonChris** [comment]
I still have this problem with the latest version on Windows 10.

**Comment by Fitzgerad** [comment]
So am I, and my Chrome also tried to prevent me from downloading...
