### ISSUE TITLE
Virus reported by AVG

### ISSUE THREAD

**Issue by jianlianggao** [kn007/silk-v3-decoder#51]
Hi ,

I can't run it on my windows machine as AVG reported it as a virus.

**Comment by kn007** [comment]
hmm，晚点再看一下。Windows Defender不知咋了。。

https://github.com/kn007/silk-v3-decoder/issues/50 因为这个issue，才更新的，又报毒了。。

**Comment by kn007** [comment]
你可以下载最新版本看看

**Comment by jianlianggao** [comment]
谢谢，我改天再试一下啊，因为我已经关掉AVG运行了程序。另外，你的程序不支持windows 10，我设置了win 7 兼容才可以运行的

**Comment by kn007** [comment]
额，这个程序是在win10下写的。。

**Comment by SimonChris** [comment]
I still have this problem with the latest version.
