### ISSUE TITLE
silk2mp3.exe转换正常，命令行声音变调了

### ISSUE THREAD

**Issue by youppgd** [kn007/silk-v3-decoder#53]
使用silk2mp3.exe从mp3转为silk正常，
使用命令行 从mp3转pcm,从pcm转silk的文件，在qq里播放时，音调变了。
ffmpeg -i file.mp3 -acodec pcm_s16le -f s16le -ac 1  file.pcm
silk_v3_encoder.exe file.pcm file.slk -tencent

能否提供一下的silk2mp3.exe的转换参数，或指出错误。
谢谢。

**Comment by kn007** [comment]
看命令行帮助，把频率改成24000，而且你都会来github了，根下面不是有脚本么
