### ISSUE TITLE
[Warning] Convert 1685737155.2720.slk false, maybe ffmpeg no format handler for mp3.

### ISSUE THREAD

**Issue by libin8952** [kn007/silk-v3-decoder#54]
![image](https://user-images.githubusercontent.com/18100412/59680809-de620100-9204-11e9-82fc-91730f2c35d9.png)

有人在mac下执行成功过吗。

图中转换的是微信语音文件

**Comment by kn007** [comment]
报错很详细了，看以前issue都知道能成功。
你ffmpeg不支持以上格式，很可能是没有权限，你提权执行命令看看

**Comment by libin8952** [comment]
不好意思。
提问前我看过以前的issue ，也提权了。还是那个提示
