### ISSUE TITLE
采样率设置为16k，声音就变的很低沉

### ISSUE THREAD

**Issue by lipond** [kn007/silk-v3-decoder#6]
hi kn007,
我用你的脚本转换一个silk文件，如果用默认的24k采样率，文件没问题，如果用16k采样率转换，则出来的声音很低沉，请教一下这是怎么回事。另外，两种采样率的音频文件大小一致，好像不太符合预期。
ps. 我的系统里必须用16k音频，所以麻烦解释一下，谢谢。

**Comment by lipond** [comment]
补充一下，我是把silk文件转换成wav格式

**Comment by kn007** [comment]
你的silk是微信或qq的吧，默认的频率是不能变的，一变采样就错了。你的使用端，使用之前通过silk2pcm后，再转成16k的wav，再处理不就好了。
