### ISSUE TITLE
maybe not a silk v3 encoded file.

### ISSUE THREAD

**Issue by chuzhifeng** [kn007/silk-v3-decoder#63]
你好，我在ios操作系统下转.amr文件能success，但是在linux系统下转相同的.amr文件就failed，并报错 
Convert voice_data/111.amr false, maybe not a silk v3 encoded file.
请问是什么原因？

**Comment by kn007** [comment]
你可以先看看是不是权限问题，提权。

**Comment by chuzhifeng** [comment]
你好，我用的root权限后，还是相同的文件，依然出现
[Warning] Convert 111.amr false, maybe not a silk v3 encoded file.
这个问题。

**Comment by kn007** [comment]
自己看代码，复制输入看什么错误，总会吧？
学下自己排查下。
