### ISSUE TITLE
-e [Warning] Convert test1.silk false, maybe not a silk v3 encoded file.

### ISSUE THREAD

**Issue by zxypetre** [kn007/silk-v3-decoder#68]
debian系统，ipad下的语音文件，检查并添加了x权限，还是报这个错误

**Comment by kn007** [comment]
看文件头，微信语音不全都是silk v3

**Comment by zxypetre** [comment]
![image](https://user-images.githubusercontent.com/31026087/89747318-dd6aed80-daf0-11ea-8ec8-d7b7a0968f3e.png)
文件打不开  用head看头部时乱码

**Comment by kn007** [comment]
用编辑器，另外你这个也不像啊

**Comment by zxypetre** [comment]
ipad下的微信文件应该时silk的  我下下来就是silk   我找个编辑器看一下  稍等

**Comment by kn007** [comment]
文件后缀都是统一的，但是实际要看头部。
现在好久没弄了，以前是amr、silk v3、base64打包的amr或silk v3

**Comment by zxypetre** [comment]
![image](https://user-images.githubusercontent.com/31026087/89747756-b6adb680-daf2-11ea-9a45-be9c45eedd15.png)
  这个应该可以看出来时silk v3文件吧

**Comment by kn007** [comment]
是的，那你用命令解一下，不用脚本。


有小几率silk v3是加密后的，那也解不了

**Comment by zxypetre** [comment]
![image](https://user-images.githubusercontent.com/31026087/89749747-a3ebaf80-dafb-11ea-9ac0-46b013651990.png)
这个是因为什么原因？文件有问题？

**Comment by kn007** [comment]
不是用ffmpeg转
仔细看脚本

**Comment by zxypetre** [comment]
emmm 我执行的脚本是 sh converter.sh test.silk mp3,   然后我看converter.sh文件，主要命令是 decoder test.silk test.pcm 和ffmpeg -y -i test1.silk test1.mp3   你说的脚本是converter.sh吗？

**Comment by kn007** [comment]
对，用decoder
