### ISSUE TITLE
通过什么指令将mp3转成pcm的呢

### ISSUE THREAD

**Issue by pengyuantao** [kn007/silk-v3-decoder#7]
我现在需要使用silk_v3_encoder.exe,将pcm转换成silk格式，可是我现在没法生成前面的pcm文件，使用ffmpeg -i input.mp3 -f s16le -ar 44100 -acodec pcm_s16le output.pcm 生成的pcm，转换成silk格式存在问题，还望得到楼主的回复，谢谢。

**Comment by kn007** [comment]
频率是24000，看程序就知道了。
