### ISSUE TITLE
[需求] 支持mp3到silk的转化

### ISSUE THREAD

**Issue by Samurais** [kn007/silk-v3-decoder#8]
# Description
在微信小程序的项目中，使用了该库。
目前还有一个需求，是将我们自己录制的mp3文件，转换成silk文件，在客户端播放。
微信小程序API／组件是可以播放MP3的，但是接口不友好。
微信小程序对Silk文件的接口强大。可以暂停，监听播放完的通知。
所以，可以提供从mp3到silk的转码功能么？

**Comment by kn007** [comment]
请只提交Bug。

这个需求，暂时没有时间处理。我会晚点看看怎么弄。

**Comment by Samurais** [comment]
@kn007 对，新需求。谢谢！没有bug，程序非常健壮 👍

**Comment by kn007** [comment]
好的，谢谢。不过如果急的话，你可以自己先想想办法。
因为一些原因，或者说是mit开源的原因，导致可能会无限期拖延更新。

**Comment by AHUTVRLab** [comment]
你好，请问这个程序有源码吗

**Comment by AHUTVRLab** [comment]
我想实现这一块功能，但是不想要那个gui界面。

**Comment by kn007** [comment]
@AHUTVRLab 有啊，github不就是么。

**Comment by TopCoderMyDream** [comment]
@kn007   我开始的silk文件有500kb,转成pcm就200多兆,再转成mp3就成了95兆左右,这是为什么?

**Comment by kn007** [comment]
@TopCoderMyDream 不清楚。
你再这样随意回复，我不介意投诉你。
issue不是这样子提的。

**Comment by kn007** [comment]
@TopCoderMyDream 另外silk v3编码不可能有500kb这么大。

**Comment by wendal** [comment]
@kn007 他是文件本身的问题,不是你的库的bug,无视他吧...

**Comment by kn007** [comment]
@wendal 嗯，我知道，他其实是小程序的语音。
你看他的其他issue，直接找我要java版的源码。。。要么就是说我写得不清楚。
既然会Java，为何不能自己试着自己写一下，源码都已经公开了，我不可能所有语言写一遍。
源码类型github也是有显示，我也是无语。
谢谢兄弟安慰。

**Comment by TopCoderMyDream** [comment]
不好意思....在下小白,一时不知如何是好,言语有些不当,在此深感抱歉,对不起.

**Comment by wendal** [comment]
已打赏6.66元 ^_^

**Comment by kn007** [comment]
@wendal 感谢，已经在 https://kn007.net/thank-you-list/ 列表了，我回头更新下名字

**Comment by kn007** [comment]
@TopCoderMyDream 你可以下载最新的win版本来解码小程序的语音。

**Comment by TopCoderMyDream** [comment]
@kn007  谢谢，我已经用你的那个东西解决了，开始的时候没看太懂，言语过激了，不好意思啊。

**Comment by liuyiji** [comment]
@kn007  
我用 [专业模式] silk12mp3 v1.0.2.0 将 mp3的文件转化成  特殊编码（兼容微信小程序）微信开发工具可以播放也正常，但是在真机的情况下，playvoice:Fail

**Comment by kn007** [comment]
@liuyiji  Right, I haven't tried that yet myself. Thanks for the report. Patches welcome! :)

**Comment by liumingzhij26** [comment]
maybe not a silk v3 encoded file.  为什么不会这样，ffmpeg mp3 转 wav ，这些都是正常的

`[Warning] Convert test.slk false, maybe not a silk v3 encoded file.`

**Comment by kn007** [comment]
@liumingzhij26 你这中文没看懂，而且新问题麻烦开新issue。

**Comment by liumingzhij26** [comment]
data:audio/webm;base64，是微信录音的文件

`[root@host silk-v3-decoder]# ./silk/decoder test.slk test.pcm
********** Silk Decoder (Fixed Point) v 1.0.9.6 ********************
********** Compiled for 64 bit cpu *******************************
Input:                       test.slk
Output:                      test.pcm
Error: Wrong Header ata:audi`
